"""
Work with Grid output from
"""
from typing import Tuple

import numpy as np
from numpy.typing import NDArray
from numpy import floating


def load_grid(filename: str) -> Tuple[NDArray[floating], NDArray[floating]]:
    """
    Loads a pair of grid files from a root name.

    Example:
        x_r10, z_r10 = load_grid('r10/')

    Arguments:
        filename: Path to the grid file generated by `py_wind`.

    Returns:
        The X and Z grid bounds.
    """
    x = np.loadtxt(filename+'grid_x.txt')
    z = np.loadtxt(filename+'grid_z.txt')
    x[0] = x[1] * 0.1
    z[0] = z[1] * 0.1
    x[-1] = x[-2] * 10
    z[-1] = z[-2] * 10
    return x, z
